[versions]
mokkery = "2.3.0-SNAPSHOT"
kotlin = "2.0.20-Beta1"  # TODO bump to stable
kotlinx-coroutines = "1.8.1"
buildconfig = "4.0.4"
google-autoservice = "1.0.1"
atomicfu = "0.24.0"
dokka = "1.9.20"
poko = "0.17.0-SNAPSHOT" # TODO bump to stable
vanniktech-publish-plugin = "0.29.0"
objensis = "3.4"
bytebuddy = "1.14.19"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }

[libraries]
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
vanniktech-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish-plugin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

buildconfig-plugin = { module = "com.github.gmazzo.buildconfig:plugin", version.ref = "buildconfig" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }

kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable" }

google-autoservice = { module = "com.google.auto.service:auto-service", version.ref = "google-autoservice"}
google-autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "google-autoservice"}

gradle-plugin-kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicfu" }

objenesis = { module = "org.objenesis:objenesis", version.ref = "objensis" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
