name: Tests Mokkery
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Builds and tests Mokkery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build --no-daemon --stacktrace
