name: Deploy Mokkery website
on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Mokkery Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - uses: gradle/gradle-build-action@v2
      - name: Install dependencies
        run: npm --prefix website ci
      - name: Build website
        run: npm --prefix website run build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build

  deploy:
    name: Deploy Mokkery Website
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
